### PR TITLE
Migrate v1 API

### PR DESCRIPTION
**Pull request by cosmo0920**
Hi, @tmtk75 !
I've tried to use brand new v1 API for Output Plugin.
Could you take a look?

If these changes are acceptable for you, please release new version as v1.0.0 instead of v0.2.0.
This PR breaks backward compatibility because brand new v1 API does not have backward compatibility.

### CODE REVIEW

**Comment by cosmo0920** [comment]
Thanks!

**Comment by tmtk75** [comment]
HI @cosmo0920,
I really appreciate your maintenance.
I've released as you said. Please check it.
https://rubygems.org/gems/fluent-plugin-sqlite3

By the way, I think I'm able to add you as owner of `fluent-plugin-sqlite3` if you'd like to frequently update the gem. Please let me know If you want.

**Comment by cosmo0920** [comment]
> By the way, I think I'm able to add you as owner of fluent-plugin-sqlite3 if you'd like to frequently update the gem. Please let me know If you want.

Sounds great!

**Comment by tmtk75** [comment]
OK, then are you using twitter?
I'm https://twitter.com/tmtk75 there. I will add you if you give me your email address via DM.

**Comment by cosmo0920** [comment]
Yep, I'm in https://twitter.com/cosmo__.
But my rubygems account email address is same as commit email address in https://github.com/tmtk75/fluent-plugin-sqlite3/commit/7d94b3219221d01610690d8ec27d97795d71c635.patch.

**Comment by cosmo0920** [comment]
Or my rubygems email address is displayed in public.
https://rubygems.org/profiles/cosmo0920

**Comment by tmtk75** [comment]
Hi, I think I added you probably. Can you take a look?
```
$ gem owner fluent-plugin-sqlite3 -a cosmo0920xxxxxx@gmail.com
Owner added successfully.
Owners for gem: fluent-plugin-sqlite3
- cosmo0920xxxxxx@gmail.com
- yyyyyyyy@gmail.com
```

**Pull request merged**
