### PR TITLE
Requirements section and buffer configuration documentation

### PR DESCRIPTION
**Pull request by cosmo0920**
I've added requirements sections in documents and add handling against old style buffer configuration.

### CODE REVIEW

**Comment by tmtk75** [comment]
Thanks a lot!
I'll merge soon.

Well, I saw this tweet, <https://twitter.com/cosmo__/status/986123067964321792>.
You are a maintainer of fluentd! awesome 🎉 
Then I think I'm ready to transfer the ownership of this repository to you since I cannot maintain this so much. Please let me know if you're OK.

**Comment by cosmo0920** [comment]
Yep, I'm willing to maintain it.

**Comment by cosmo0920** [comment]
> So let me know if you want to be transferred after deleting.

I've deleted the fork repository under my GH account.

**Comment by cosmo0920** [comment]
Thanks!
I've confirmed that repository had been transferred. :smile:

**Comment by tmtk75** [comment]
🎉Great
It's the first time to transfer ownership to me. It's interesting.
Thanks a lot to take care of my code 🙇 @cosmo0920

**Pull request merged**
